name: navigation
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  auto_route: ^5.0.4
  flutter:
    sdk: flutter

  core:
    git:
      url: https://github.com/Mobile-Innowise-Group/DevPilotTemplates.git
      path: core
  core_ui:
    git:
      url: https://github.com/Mobile-Innowise-Group/DevPilotTemplates.git
      path: core_ui
  domain:
    git:
      url: https://github.com/Mobile-Innowise-Group/DevPilotTemplates.git
      path: domain

dev_dependencies:
  flutter_lints: 2.0.1
  dart_code_metrics: 5.5.1
  auto_route_generator: 5.0.3
  build_runner: 2.3.3