name: plug
description: Home feature
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    git:
      url: https://github.com/Mobile-Innowise-Group/DevPilotTemplates.git
      path: core
  domain:
    git:
      url: https://github.com/Mobile-Innowise-Group/DevPilotTemplates.git
      path: domain
  core_ui:
    git:
      url: https://github.com/Mobile-Innowise-Group/DevPilotTemplates.git
      path: core_ui
  navigation:
    git:
      url: https://github.com/Mobile-Innowise-Group/DevPilotTemplates.git
      path: navigation


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
