name: core
version: 0.0.1
publish_to: none
description: Project core module

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    git:
      url: https://github.com/RomanPreis/DevPilotTemplates.git
      path: data
  domain:
    git:
      url: https://github.com/RomanPreis/DevPilotTemplates.git
      path: domain
  navigation:
    git:
      url: https://github.com/RomanPreis/DevPilotTemplates.git
      path: navigation

  get_it: ^7.2.0
  dio: ^5.1.1
  logger: ^1.3.0
  flutter_bloc: ^8.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
